apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  selector:
    matchLabels:
      app: test
      type: testing
  replicas: 2
  template:
    metadata:
      labels:
        app: test
        type: testing
    spec:
      containers:
        - name: nginx
          image: prachiacr.azurecr.io/testing:v1.0.2
          ports:
            - containerPort: 8080
##testing semantic